module AnimatedDistributions

using Random, Distributions, Plots, GR, ColorSchemes, PlotThemes

export animate_beta # Beta distribution

include("animate_beta.jl")
include("animate_normal.jl")
include("save_animation.jl")

end # module

"""
A Julia package for animating probability distributions implemented in Distributions.jl.
API overview (major features):
- `animate_*(x, ...)` creates an animation for a given range of values of the sampling space and one vector of values for each of its parameters.
- `save_animation(animation, path, fps)` saves an animation generated by one of the `animate_*` functions and saves it as a .gif file in the specified path. 

Users are encouraged to refer to the full documentation at
https://gongcastro.github.io/AnimatedDistributions.jl/ and https://JuliaStats.github.io/Distributions.jl/stable/ for further for further information.

"""
