module AnimatedDistributions

using Random, Distributions, Plots, GR

export animate_beta,
    animate_normal,
    animate_cauchy,
    animate_weibull,
    animate_gamma,
    animate_frechet,
    animate_rayleigh,
    animate_invgamma,
    animate_exponential,
    animate_pareto,
    animate_semicircle,
    animate_tstudent,
    animate_triweight

include("animate_beta.jl")
include("animate_normal.jl")
include("animate_gamma.jl")
include("animate_invgamma.jl")
include("animate_frechet.jl")
include("animate_weibull.jl")
include("animate_rayleigh.jl")
include("animate_cauchy.jl")
include("animate_exponential.jl")
include("animate_pareto.jl")
include("animate_tstudent.jl")
include("animate_triweight.jl")
include("animate_semicircle.jl")
include("save_animation.jl")

end # module

"""
A Julia package for animating probability distributions implemented in Distributions.jl.
API overview (major features):
- `animate_*(x, ...)` creates an animation for a given range of values of the sampling space and one vector of values for each of its parameters.
- `save_animation(animation, path, fps)` saves an animation generated by one of the `animate_*` functions and saves it as a .gif file in the specified path. 

Users are encouraged to refer to the full documentation at
https://gongcastro.github.io/AnimatedDistributions.jl/ and https://JuliaStats.github.io/Distributions.jl/stable/ for further for further information.

"""
